# global ints

# window IDs
WMAIN = 0
WACTION = 1
WTERMINAL = 2


# keyboard shortcuts
__layout = 2
__CTRL_LEFT_1 = 545
__CTRL_RIGHT_1 = 560
__CTRL_UP_1 = 566
__CTRL_DOWN_1 = 525
__CTRL_PG_UP_1 = 555
__CTRL_PG_DOWN_1 = 550

__CTRL_LEFT_2 = 546
__CTRL_RIGHT_2 = 561
__CTRL_UP_2 = 567
__CTRL_DOWN_2 = 526
__CTRL_PG_UP_2 = 556
__CTRL_PG_DOWN_2 = 551

if __layout == 1:
    CTRL_LEFT = __CTRL_LEFT_1
    CTRL_RIGHT = __CTRL_RIGHT_1
    CTRL_PG_UP = __CTRL_PG_UP_1
    CTRL_UP = __CTRL_UP_1
    CTRL_DOWN = __CTRL_DOWN_1
    CTRL_PG_DOWN = __CTRL_PG_DOWN_1
else:
    CTRL_LEFT = __CTRL_LEFT_2
    CTRL_RIGHT = __CTRL_RIGHT_2
    CTRL_PG_UP = __CTRL_PG_UP_2
    CTRL_UP = __CTRL_UP_2
    CTRL_DOWN = __CTRL_DOWN_2
    CTRL_PG_DOWN = __CTRL_PG_DOWN_2