# add commands
add:
  account:
    args: {'name':'str', 'initial_balance':'float'}
    desc: "add an account and its corresponding database table"
    task-id: 101
  expense:
    args: ['chronological':'bool']
    desc: "enter expense mode"
    task-id: 102

# list commands
list:
  accounts:
    args: {}
    desc: "list all the accounts"
    task-id: 201

# set commands
set:
  account:
    args: {'name':'str'}
    desc: "set the current account"
    task-id: 301

# parse commands
parse:
  mkcsv:
    args: {'file_path':'str', 'translate_categories':'bool'}
    desc: "parse a .csv file & add it to current database"
    task-id: 401

# delete commands 
delete:
  account:
    args: {'name':'str'}
    desc: "delete the account"
    task-id: 501

# show commands
show:
  all:
    args: {}
    desc: "show all expenses"
    task-id: 601
  monthly:
    args: {}
    desc: "show monthly expenses"
    task-id: 602

### terminal specific tasks:
# exit
exit:
  args: {}
  desc: "exit the program"
  task-id: 100001

# clear
clear:
  args: {}
  desc: "clear the terminal"
  task-id: 100002
