# add commands
add:
  account:
    args: {'name':'str', 'initial_balance':'float'}
    desc: "add an account and its corresponding database table"
    task-id: 101
  expense:
    args: []
    desc: "enter expense mode"
    task-id: 102

# list commands
list:
  accounts:
    args: {}
    desc: "list all the accounts"
    task-id: 201

# set commands
set:
  account:
    args: {'name':'str'}
    desc: "set the current account"
    task-id: 301

# parse commands
parse:
  csv:
    args: {'file_path':'str', 'translate_categories':'bool'}
    desc: "parse a .csv file & add it to current database"
    task-id: 401

# delete commands 
delete:
  account:
    args: {'name':'str'}
    desc: "delete the account"
    task-id: 501

# exit
exit:
  args: {}
  desc: "exit the program"
  task-id: 666

