# add commands
add:
  account:
    args: {'name':'str', 'initial_balance':'float'}
    desc: "add a bank account and its corresponding database table"
    task-id: 1
  expense:
    args: []
    desc: "enter expense mode"
    task-id: 2

# list commands
list:
  accounts:
    args: {}
    desc: "list all the bank accounts"
    task-id: 3

# set commands
set:
  account:
    args: {'name':'str'}
    desc: "sets the current account"
    task-id: 4

# parse commands
parse:
  csv:
    args: {'file_path':'str', 'translate_categories':'bool'}
    desc: "parse a .csv file & add it to current database"
    task-id: 5

