# transaction table column sizes
table:
  index-length-percentage: 5
  amount-length-percentage: 10
  category-length-percentage: 12
  subcategory-length-percentage: 12
  payee-length-percentage: 10
  note-length-percentage: 30
  scrollbar-enable: true

# recurring transaction settings
recurring:
  months: 6
  significance-ratio: 0.7
  discard-limit: 3
  min-occurance: 5

# window sizes
main:
  x: 5 # w.r.t. screen
  y: 3 # w.r.t. screen
  list-x-offset: 2 # w.r.t. main window
  list-y-offset: 5 # w.r.t. main window
  width-percentage: 0.80
  height-percentage: 0.75

action:
  x-offset: 2 # w.r.t. main window
  y: 3 # w.r.t. screen
  width-percentage: 0.15
  height-percentage: 0.75

terminal:
  x: 5 # w.r.t. screen
  y-offset: 1 # w.r.t. main window
  width-offset: -5
  height-percentage: 0.2
  command-history-buffer-length: 50

application:
  warm-up: true
  use-jdate: false
  enable-utf8-support: false
  command-history-file-length: 20
  stack-trace-on-warmup-error: true